name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  code_verification:
    steps:
      - name: Linting
        run: yarn lint
      - name: Build
        run: yarn build
  unit_tests:
    needs:
      - code_verification
    steps:
      - name: Run unit tests
        run: yarn test
