version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  verify-code:
    executor: node/default
    steps:
      - checkout
      - run: yarn lint
      - run: yarn test

non_master: &non_master
  filters:
    branches:
      ignore: master

master_only: &master_only
  filters:
    branches:
      only: master

workflows:
  development:
    jobs:
      - verify-code:
          <<: *non_master
  production:
    jobs:
      - verify-code:
          <<: *master_only

