name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  project_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn
      - run: yarn install
  code_verification:
    runs-on: ubuntu-latest
    needs:
      - project_setup
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Linting
        run: yarn lint
      - name: Build
        run: yarn build
  unit_tests:
    runs-on: ubuntu-latest
    needs:
      - code_verification
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Unit tests
        run: yarn test
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs:
      - code_verification
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
